version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: moviebooking-mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moviebooking-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: moviebooking-backend-prod
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "8080"
    depends_on:
      - mysql
    networks:
      - moviebooking-network
    restart: always

  # Nginx (Frontend + Reverse Proxy)
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: moviebooking-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - moviebooking-network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/ssl/certs
    restart: always

volumes:
  mysql_data:

networks:
  moviebooking-network:
    driver: bridge